
services:
  backend:
    # IMPORTANT: Replace 'yourdockerhubusername' with your actual Docker Hub username.
    image: yourdockerhubusername/chatapp-backend:latest
    restart: unless-stopped
    env_file: ./.env
    depends_on:
      - mongo
      - redis

  frontend:
    # IMPORTANT: Replace 'yourdockerhubusername' with your actual Docker Hub username.
    image: yourdockerhubusername/chatapp-frontend:latest
    restart: unless-stopped

  # 3. The Nginx Reverse Proxy (The main entry point for all traffic)
  nginx:
    image: nginx:1.29.0-alpine
    ports:
      - "80:80"   # Public-facing port
      - "443:443" # For SSL later
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/private:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  # 4. The MongoDB Database Service
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  # 5. The Redis Caching Service
  redis:
    image: redis:7.4
    restart: unless-stopped

# These volumes are managed by Docker to persist data.
volumes:
  mongo-data:
