version: '3.8'

services:
  backend:
    # IMPORTANT: Replace 'yourdockerhubusername' with your actual Docker Hub username.
    image: yourdockerhubusername/chatapp-backend:latest
    restart: unless-stopped
    env_file: ./.env
    depends_on:
      - mongo
      - redis

  frontend:
    # IMPORTANT: Replace 'yourdockerhubusername' with your actual Docker Hub username.
    image: yourdockerhubusername/chatapp-frontend:latest
    restart: unless-stopped

  # 3. The Nginx Reverse Proxy (The main entry point for all traffic)
  nginx:
    image: nginx:1.29.0-alpine
    ports:
      - "80:80"   # Public-facing port
      - "443:443" # For SSL later
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-certs:/etc/letsencrypt
      - webroot:/var/www/html
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  # 4. The MongoDB Database Service
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  # 5. The Redis Caching Service
  redis:
    image: redis:7.4
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - certbot-certs:/etc/letsencrypt
      - webroot:/var/www/html

# These volumes are managed by Docker to persist data.
volumes:
  mongo-data:
  certbot-certs:
  webroot:

