name: Deploy to EC2 with Docker



on:

  push:

    branches: [ "main" ] 



jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code

        uses: actions/checkout@v4



      - name: Login to Docker Hub

        uses: docker/login-action@v3

        with:

          username: ${{ secrets.DOCKERHUB_USERNAME }}

          password: ${{ secrets.DOCKERHUB_TOKEN }}



      - name: Build and Push Backend Image

        uses: docker/build-and-push-action@v5

        with:

          context: ./Backend

          push: true

          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chatapp-backend:latest



      - name: Build and Push Frontend Image

        uses: docker/build-and-push-action@v5

        with:

          context: ./Frontend

          push: true

          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chatapp-frontend:latest



      - name: Deploy to EC2

        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.EC2_HOST }}

          username: ${{ secrets.EC2_USER }}

          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            cd ~/Chat-App

            ./deploy.sh 
